[tool.poetry]
name = "port-backend"
version = "0.1.0"
description = ""
authors = ["Jorge Mendes <mende012@moura002>"]


[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.1"
uvicorn = "^0.27.0.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
